authen/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import DetailView, TemplateView
urlpatterns = patterns('myproject.authen.views',


    ###****questions************
    url(r'^signup/new/$', 'signup'),
    url(r'^enter/image/(\d+)/$', 'cbtimage'),
   url(r'^activate/user/$', 'activate'),
   # url(r'^login/me/$', 'mylogin'),
   url(r'^login/student/$','studentlogin'),
    url(r'^subject/choice/$', 'ssubchoice'),

    )

urls.py
from django.conf.urls.defaults import *
from myproject.signals import *
from django.conf import settings
from myproject.sysadmin.views import *
from myproject.setup.views import *
from myproject.utilities.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', index),studentlogin
    # url(r'^login/$', index),


    url(r'^$', studentlogin),
    url(r'^login/$', studentlogin),

    url(r'^login/admin/$', index),

    url(r'^header/$', header),
    url(r'^welcome/$', welcomecode),
    url(r'^online/$', online_result),
    url(r'^subject_report/$', subject_report),
    url(r'^student_search/$', search_student),
    url(r'^logout/$', logoutuser),
    url(r'^unauthorised/$', unatho),
    url(r'^uploadlga/$',uploadlocal ),
    url(r'^uploadsubgroup/$',uploadaccsubgrp),
    url(r'^uploadacc/$',uploadacc),
    url(r'^home_dashboard/$',dashboard),
    url(r'^uploadtransaction/$',uploadtransaction),
    url(r'^pass_change/$', change_password),
    url(r'^getchangepassword/$', getchangepassword),
    url(r'^uploadstudent/$',uploadstudent),
    url(r'^uploadbill/$',uploadbill),#to upload bill setup
    url(r'^uploadbillname/$',uploadbillname),#to upload bill name
    url(r'^uploadadditionalbill/$',uploadadditionalbill),#to upload  additional bills
    url(r'^uploadpostedbill/$',uploadpostedbill),#to upload posted bill

    url(r'^changepassword/$', changepassword),
    url(r'^setup/', include('myproject.setup.urls')),
    url(r'^student/', include('myproject.student.urls')),
    url(r'^bill/', include('myproject.bill.urls')),
    url(r'^cbt/', include('myproject.CBT.urls')),
    url(r'^sysadmin/', include('myproject.sysadmin.urls')),
    url(r'^controllers/', include('myproject.sysadmin.urls')),
    url(r'^assessment/', include('myproject.assessment.urls')),

    url(r'^lesson/', include('myproject.lesson.urls')),
    url(r'^authen/', include('myproject.authen.urls')),

    url(r'^assignment/', include('myproject.assignment.urls')),
   # url(r'^transport/', include('myproject.transport.urls')),
    url(r'^utils/', include('myproject.utilities.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
   # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),

    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

CBT/forms.py
from django import forms
from myproject.setup.models import *
from myproject.sysadmin.models import *
from myproject.student.models import *
from myproject.lesson.models import *
from myproject.CBT.models import *


def sess():
    return currentsession.objects.get(id = 1)

sess = currentsession.objects.get(id = 1)
exam = (('Welcome back', 'Welcome back'),('Mid Term Exam', 'Mid Term Exam'),('Ca2' , 'Ca2'),('End Term Exam', 'End Term Exam'))



class subform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10','readonly':'readonly'}),initial=sess)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    user = forms.CharField(label = "User",max_length = 20,required = True,widget = forms.TextInput())
    subject = forms.ChoiceField(label= 'Subject', choices = [(a.subject, a.subject) for a in Subject.objects.all()])


    def __init__(self, *args, **kwargs):
        super(subform, self).__init__(*args)
        self.fields['user'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['subject'].choices = [(a.subject, a.subject) for a in Subject.objects.all()]
        self.fields['subject'].initial = Subject.objects.all()
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'


class printform(forms.Form):#note that is this CA term that need to come from back end
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10','readonly':'readonly'}),initial=sess)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=[(a.term, a.term) for a in tblterm.objects.all()])
    arm = forms.ChoiceField(label= 'Arm', choices = [(a.arm, a.arm) for a in Arm.objects.all()])
    subject = forms.ChoiceField(label= 'Subject', choices = [(a.subject, a.subject) for a in Subject.objects.all()])
    exam_type = forms.ChoiceField(label= 'Exam Type', choices = [(r.exam_type, r.exam_type) for r in tblcbtexams.objects.all()])

    def __init__(self, *args):
        super(printform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['arm'].choices = [(a.arm, a.arm) for a in Arm.objects.all()]
        self.fields['arm'].initial = Arm.objects.all()
        self.fields['subject'].choices = [(a.subject, a.subject) for a in Subject.objects.all()]
        self.fields['subject'].initial = Subject.objects.all()
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]
        # self.fields['reporttype'].choices = [(a.reportsheet, a.reportsheet) for a in tblreportsheet.objects.filter(status = 'ACTIVE')]



class assessmentform(forms.Form):
    assess = forms.ChoiceField(label='Assessment Type',choices = [(a.exam_type, a.exam_type) for a in tblcbtexams.objects.all()])
    status = forms.ChoiceField(label='Status',choices=( ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')))



class stuform(forms.Form):#note that is this CA term that need to come from back end
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10','readonly':'readonly'}),initial=sess)
    term = forms.ChoiceField(label='Term',choices=[(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')])
    subject = forms.ChoiceField(label= 'Subject', choices = [(a.subject, a.subject) for a in Subject.objects.all()])
    exam_type = forms.ChoiceField(label='Exam Type',choices = [(a.exam_type, a.exam_type) for a in tblcbtexams.objects.all()])
    def __init__(self, *args):
        super(stuform, self).__init__(*args)
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]
        self.fields['term'].initial = tblterm.objects.filter(status = 'ACTIVE')




class formactive(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10','readonly':'readonly'}),initial=sess)
    sfrom = forms.ChoiceField(label='From',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    sto = forms.ChoiceField(label='To',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices = [(c.term, c.term) for c in tblterm.objects.all()])
    exam_type = forms.ChoiceField(label='Exam Type',choices = [(a.exam_type, a.exam_type) for a in tblcbtexams.objects.all()])
    subject = forms.ChoiceField(label= 'Subject', choices = [(a.subject, a.subject) for a in Subject.objects.all()])
    duration = forms.CharField(label='Duration',max_length= 190,required=True)

    def __init__(self, *args):
        super(formactive, self).__init__(*args)
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'


class qstnform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10','readonly':'readonly'}),initial=sess)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    subject=forms.ChoiceField(label= 'Subject', choices = [(a.subject, a.subject) for a in Subject.objects.all()])
    term = forms.ChoiceField(label='Term',choices = [(c.term, c.term) for c in tblterm.objects.filter(status= 'ACTIVE')])
    exam_type = forms.ChoiceField(label='Exam Type',choices = [(a.exam_type, a.exam_type) for a in tblcbtexams.objects.all()])
    question = forms.CharField(label= 'Question', max_length= 99190)
    pix = forms.ImageField(required=False,widget=forms.FileInput(attrs={'size':'5'}),label='Student Picture')
    


    def __init__(self, *args):
        super(qstnform, self).__init__(*args)
        self.fields['session'].choices = [(c.session, c.session) for c in currentsession.objects.filter(id = 1)]
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]

authen/forms.py
from django import forms


exam = (('Select One', 'Select One'),
  ('JAMB PREP', 'JAMB PREP'),
  ('WAEC', 'WAEC'),('NECO', 'NECO'),
  ('GCE', 'GCE'),('NABTEB', 'NABTEB'),
  ('POST UTME', 'POST UTME'),('JUPEB', 'JUPEB'),
  ('IJMB', 'IJMB'),('JOINT PROMOTION EXAM', 'JOINT PROMOTION EXAM'),
  ('APTITUDE TEST', 'APTITUDE TEST'),('ENTRANCE EXAM', 'ENTRANCE EXAM'),
  ('RECRUITMENT EXAM', 'RECRUITMENT EXAM'),('SCREANING EXAM', 'SCREANING EXAM'),
  ('OTHER','OTHER'),
  )




class signupform(forms.Form):
    username = forms.CharField(label='Username')
    email = forms.EmailField(label='E-mail',max_length=50)
    exam = forms.ChoiceField(label= 'Exam', choices = exam)
    password = forms.CharField(label="Password",widget=forms.PasswordInput,required = True)

      # def __init__(self, *args, **kwargs):
      #    super(loginform, self).__init__(*args, **kwargs)
      #    self.fields['username'].widget.attrs['class'] = 'loginTxtbox'




    def __init__(self, *args, **kwargs):
        super(signupform, self).__init__(*args, **kwargs)
        self.fields['password'].widget.attrs['class'] = 'loginTxtbox'


class loginform(forms.Form):
      email = forms.CharField(label="Email",required = True)
      password = forms.CharField(label="Password",widget=forms.PasswordInput,required = True)

      def __init__(self, *args, **kwargs):
         super(loginform, self).__init__(*args, **kwargs)
         self.fields['email'].widget.attrs['class'] = 'loginTxtbox'
         self.fields['password'].widget.attrs['class'] = 'loginTxtbox'

forms.py
from django import forms
from myproject.setup.models import *
from myproject.sysadmin.models import *
from myproject.student.models import *

currse = currentsession.objects.get(id = 1)

class caform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10','readonly':'readonly'}),initial=currse)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=( ('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    arm = forms.ChoiceField(label= 'Arm', choices = [(a.arm, a.arm) for a in Arm.objects.all()])
    subject = forms.ChoiceField(label= 'Subject', choices = [(a.subject, a.subject) for a in Subject.objects.all()])

    def __init__(self, *args):
        super(caform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['arm'].choices = [(a.arm, a.arm) for a in Arm.objects.all()]
        self.fields['arm'].initial = Arm.objects.all()
        self.fields['subject'].choices = [(a.subject, a.subject) for a in Subject.objects.all()]
        self.fields['subject'].initial = Subject.objects.all()
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'

class addsubjectform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10','readonly':'readonly'}),initial=currse)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=( ('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    arm = forms.ChoiceField(label= 'Arm', choices = [(a.arm, a.arm) for a in Arm.objects.all()])
    student = forms.ChoiceField(label= 'Student', choices = [(a.fullname, a.fullname) for a in Student.objects.filter(admitted_session =currse)])

    def __init__(self, *args):
        super(addsubjectform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['arm'].choices = [(a.arm, a.arm) for a in Arm.objects.all()]
        self.fields['arm'].initial = Arm.objects.all()
        self.fields['student'].choices = [(a.fullname, a.fullname) for a in Student.objects.filter(admitted_session =currse)]
        self.fields['student'].initial = Student.objects.filter(admitted_session =currse)
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'

class reportsheetform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10'}),initial=currse)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    arm = forms.ChoiceField(label= 'Arm', choices = [(a.arm, a.arm) for a in Arm.objects.all()])
    pdffile = forms.BooleanField(label='Download In PDF',required=False)
    def __init__(self, *args):
        super(reportsheetform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['arm'].choices = [(a.arm, a.arm) for a in Arm.objects.all()]
        self.fields['arm'].initial = Arm.objects.all()
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'

class broadsheetform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10'}),initial=currse)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    def __init__(self, *args):
        super(broadsheetform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'

authen/views.py
from myproject.authen.forms import *
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from myproject.authen.models import *


def signup(request):
	if request.method=='POST':
		form = signupform(request.POST)
		if form.is_valid():
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			exam=form.cleaned_data['exam']
			email=form.cleaned_data['email']

			userid = userprofile.objects.filter(username=username).count()
			if userid==0:
				userprofile(username=username,email=email,password=password,exam=exam).save()
				return render_to_response('authen/success.html')

			else:		
				msg = 'username already exist'
				return HttpResponseRedirect('/authen/signup/new/')
		
		else:
			form=signupform()
			return render_to_response('authen/signup.html',{'form':form})
	
	else:
		form = signupform()
	return render_to_response('authen/signup.html',{'form':form})


def studentlogin(request):
	if request.method=='POST':
		form=loginform(request.POST)
		if form.is_valid():
			email=form.cleaned_data['email']
			password=form.cleaned_data['password']
		else:
			msg = 'enter all details'
			return render_to_response('loginstu.html')
		
		try:
			k = userprofile.objects.get(email=email,password=password)
		except:
			return HttpResponseRedirect('/login/')
		try:
			j=tblpayment.objects.get(email=email,stream='Stream 1', exam='JAMB PREP')
			
		except:
			return HttpResponseRedirect('/authen/activate/user/')

		# except:
		# 	return HttpResponseRedirect('/loginstu/')


	else:
		form=loginform()
	return render_to_response('loginstu.html',{'form':form})
		


		
def activate(request):
	if request.method=='POST':
		pass
	else:
		return render_to_response('authen/activate.html')

authen/templates/authen/activate.html
<html>


<script type="text/javascript" src='/static/JS/jquery-1.5.js'></script>


{% extends 'authen/base.html' %}
{% block sectionTitle %}Success{% endblock %}

{% block content %}

 <div  style="background-color:#ccccc0;border:0px solid black;width:100%;height:25px; font-size:14px;color:black;text-align:center;padding-top:5px;">Acount Activation </div>


       <table style="margin-top:01%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">

    <tr style="text-align:center">
        <td >
           <a href="#"  >Signed Up <i class="fa fa-check fa-fw"></i></a>
        </td>
        <td style='background:blue'>
            <a href="/authen/activate/user/" style='color:white'><i class="fa fa-gear fa-fw"></i>Acivate</a>
        </td>
        <td >
           <a href="/authen/subject/choice/" > Subject Choice</a><i class="fa fa-close fa-fw"></i>
        </td>

    </tr>


</table>



<tr>
    <table style="margin-top:0%;margin-bottom:0%"  width="100%" class="table  table-bordered" id="dataTables-example">
        <div>your account is not yet activated</div>
    </table>
</tr>

 <tr>
     <table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">
      <div>To activate your account, pay the sum of <span style='color:blue'>N1,000</span> to the account below</div>
    </table>
</tr>
<div style="font-weight:bold">
    <div>Bank: UBA Bank</divi>
    <div>Account: 2080861508</div>
    <div>Account Name: Okeke Collins</div>
    <div>After payment, click here <a href="https://wa.me/23409061287894">  09061287894  </a>to activate your account</div>
</div>
</html>

{% endblock %}

authen/templates/authen/signup.html
<script type="text/javascript" src='/static/JS/jquery-1.5.js'></script>


{% extends 'authen/signupbase.html' %}
{% block sectionTitle %}Success{% endblock %}

{% block content %}


       <table style="margin-top:01%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">

    <tr style="text-align:center">
        <td style='background:blue'>
           <div style='color:white'>Sign Up Form</div>
        </td>
<!--         <td>
            <a href="/authen/activate/user/"><i class="fa fa-gear fa-fw"></i>Acivate</a>
        </td>
        <td >
           <a href="/authen/subject/choice/" ><i class="fa fa-tasks fa-fw"></i> Subject Choice</a>
        </td> -->

    </tr>


</table>




               <form action="" method="POST">
                  <table width="100%" class="table  table-bordered" id="dataTables-example">
                   <tr >
                       <td >{{ form.username.label_tag }}:</td>
                       <td> {{ form.username }}</td>
                    </tr>
                    <tr>
                       <td >{{ form.email.label_tag }}:</td>
                       <td> {{ form.email }}</td>
                    </tr>
                    <tr>
                     <td >{{ form.exam.label_tag }}:</td>
                     <td>{{ form.exam }}</td>
                </tr>
                <tr>
                       <td >{{ form.password.label_tag }}:</td>
                       <td>{{ form.password }}</td >

                </tr>
                <tr>
             <table style="margin-top:0%;margin-bottom:3%" width="100%" class="table  table-bordered table-hover" id="dataTables-example">
                          <input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="Sign Up">
                    </table>

                   </tr>
               </table>
               </form>
                    <a href="/logout/"><i class="fa fa-sign-out fa-fw"></i>Log in</a>

    <table width="100%" class="table  table-bordered" id="dataTables-example">

            <td colspan="20" >

                <div class="box2">
                </div>
            </td>

    </table>

    <div id="regform" style="width: 100%;"></div>


    <script>
        $(document).ready(function() {
            var pickerOpts = {
                //appendText: "mm/dd/yy",
                //defaultDate: "+5",
                showOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat:"yy-mm-dd"
            };

            getclass();
            //getarm();
            // getterm();
        });
    </script>

   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_subject").change(function () {
                autopost2();
            });
            $("#id_arm").change(function () {
                getsubject();
            });
            $("#id_sfrom").change(function () {
                getclass();
            });
            $("#id_term").change(function () {
                autopost2();
            });
        });
    </script>

    <script type="text/javascript" language="javascript">
        function getclass(){
            var state = $("#id_sfrom").val(); // i need session to determine my class
            // alert(state);
            var state = state.substr(0,1);
            // alert(state);
            var url = "/cbt/getcbtklass/";
            var i = 0;
            var data='userid='+state;
            $("#id_sto").val('');
            $("#id_sto").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_sto").append(options);
                        getterm();

                    }
                })
            }
        }

    </script>


   <script type="text/javascript" language="javascript">
        function getterm(){
            var state = $("#id_session").val() ;
            // alert(state);
            var url = "/assessment/getterm/";
            var i = 0;
            var data='userid='+state;
            $("#id_term").val('');
            $("#id_term").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_term").append(options);
                        accessment();
                    }
                })
            }
        }

    </script>
    <script type="text/javascript" language="javascript">
        function accessment(){
            var state = $("#id_session").val();
            var url = "/cbt/assess/getassess/";
            var i = 0;
            var data='userid='+state;
            $("#id_exam_type").val('');
            $("#id_exam_type").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_exam_type").append(options);
                        getsubject();
                    }
                })
            }
        }

    </script>

    <script type="text/javascript" language="javascript">
        function getsubject(){
            //var state = $("#id_session").val() ;
            var state = $("#id_sfrom").val();
            var state = state.substr(0,2);
            // alert(state);
            var url = "/cbt/getsubject/";
            var i = 0;
            var data='userid='+state;
            $("#id_subject").val('');
            $("#id_subject").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_subject").append(options);
                        autopost2();
                    }
                })
            }
        }

    </script>

    <script type="text/javascript" language="javascript">
        function autopost2(){
            var state = $("#id_sfrom").val()+':'+ $("#id_exam_type").val() +':'+ $("#id_term").val()+':'+ $("#id_subject").val() ;
            var url = "/cbt/getscheduledsubject/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    $(".box2").show();
                    $(".box2").html(html);

                }
            });
            return false;
        }
    </script>

{% endblock %}

authen/templates/authen/subjectselect.html
<html>


<script type="text/javascript" src='/static/JS/jquery-1.5.js'></script>


{% extends 'authen/base.html' %}
{% block sectionTitle %}Success{% endblock %}

{% block content %}

 <div  style="background-color:#ccccc0;border:0px solid black;width:100%;height:25px; font-size:14px;color:black;text-align:center;padding-top:5px;">Acount Activation </div>



       <table style="margin-top:01%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">

    <tr style="text-align:center">
        <td >
           <a href="#"  >Signed Up <i class="fa fa-check fa-fw"></i></a>
        </td>
        <td >
            <a href="/authen/activate/user/" >Acivate<i class="fa fa-check fa-fw"></i></a>
        </td>
        <td  style='background:blue'>
           <a href="/authen/subject/choice/" style='color:white'> Subject Choice</a>
        </td>

    </tr>


</table>


<tr>
    <table style="margin-top:0%;margin-bottom:0%"  width="100%" class="table  table-bordered" id="dataTables-example">
        <div>your account is not yet activated</div>
    </table>
</tr>

 <tr>
     <table style="margin-top:0%;margin-bottom:0%" width="100%" class="table  table-bordered" id="dataTables-example">
      <div>To activate your account, pay the sum of <span style='color:blue'>N1,000</span> to the account below</div>
    </table>
</tr>
<div style="font-weight:bold">
    <div>Bank: UBA Bank</divi>
    <div>Account: 2080861508</div>
    <div>Account Name: Okeke Collins</div>
    <div>After payment, click here <a href="https://wa.me/23409061287894">  09061287894  </a>to activate your account</div>
</div>
</html>

{% endblock %}

authen/templates/authen/success.html
{% extends 'authen/base.html' %}
{% block sectionTitle %}Success{% endblock %}
{% block content %}

   <span style="font-size:20px;color:black;text-align:center;"><br>Congratulations, account created successfully </span>

<div>Follow this <a href="/authen/login/student/">link</a>  to log in</div>

 {% endblock %}