assignment/urls.py
from django.conf.urls.defaults import patterns, url



urlpatterns = patterns('myproject.assignment.views',
    # Examples:
    url(r'^assignment/$', 'choose'),
    url(r'^t/pa/$', 'assignment'),
    url(r'^s/pj/$', 'studassign'),

    )

urls.py
from django.conf.urls.defaults import *
from myproject.signals import *
from django.conf import settings
from myproject.sysadmin.views import *
from myproject.setup.views import *
from myproject.utilities.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', index),studentlogin
    # url(r'^login/$', index),


    url(r'^$', studentlogin),
    url(r'^login/$', studentlogin),

    url(r'^login/admin/$', index),

    url(r'^header/$', header),
    url(r'^welcome/$', welcomecode),
    url(r'^online/$', online_result),
    url(r'^subject_report/$', subject_report),
    url(r'^student_search/$', search_student),
    url(r'^logout/$', logoutuser),
    url(r'^unauthorised/$', unatho),
    url(r'^uploadlga/$',uploadlocal ),
    url(r'^uploadsubgroup/$',uploadaccsubgrp),
    url(r'^uploadacc/$',uploadacc),
    url(r'^home_dashboard/$',dashboard),
    url(r'^uploadtransaction/$',uploadtransaction),
    url(r'^pass_change/$', change_password),
    url(r'^getchangepassword/$', getchangepassword),
    url(r'^uploadstudent/$',uploadstudent),
    url(r'^uploadbill/$',uploadbill),#to upload bill setup
    url(r'^uploadbillname/$',uploadbillname),#to upload bill name
    url(r'^uploadadditionalbill/$',uploadadditionalbill),#to upload  additional bills
    url(r'^uploadpostedbill/$',uploadpostedbill),#to upload posted bill

    url(r'^changepassword/$', changepassword),
    url(r'^setup/', include('myproject.setup.urls')),
    url(r'^student/', include('myproject.student.urls')),
    url(r'^bill/', include('myproject.bill.urls')),
    url(r'^cbt/', include('myproject.CBT.urls')),
    url(r'^sysadmin/', include('myproject.sysadmin.urls')),
    url(r'^controllers/', include('myproject.sysadmin.urls')),
    url(r'^assessment/', include('myproject.assessment.urls')),

    url(r'^lesson/', include('myproject.lesson.urls')),
    url(r'^authen/', include('myproject.authen.urls')),

    url(r'^assignment/', include('myproject.assignment.urls')),
   # url(r'^transport/', include('myproject.transport.urls')),
    url(r'^utils/', include('myproject.utilities.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
   # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),

    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

assignment/models.py
from django.db import models
#from django.contrib.admin.models import User

class tblassignment(models.Model):
	teacher = models.CharField('Teacher', max_length=75)
	subject = models.CharField('Subject', max_length=75)
	klass = models.CharField('class', max_length=75)
	arm = models.CharField('Arm', max_length=75)
	term = models.CharField('Term', max_length=75)
	session = models.CharField('Session', max_length=75)
	assignment = models.CharField('Assignment', max_length=5000)
	comment = models.CharField('Comment', max_length=5000)
	posted_on = models.DateField('Posted Date')
	submit_on = models.DateField('Submission Date')
	ass_file= models.FileField('Assignment File', upload_to='ax', null=True,blank=True)



	def __unicode__(self):
		return u' teacher : %s ,Subject : %s , assignment : %s , posted_on  : %s' % (self.teacher,self.subject,self.assignment,self.posted_on)



class tblspec(models.Model):
	teacher = models.CharField('Teacher', max_length=75)
	subject = models.CharField('Subject', max_length=75)
	name = models.CharField('Name', max_length=75)
	session = models.CharField('Session', max_length=75)
	assignment = models.CharField('Assignment', max_length=5000)
	comment = models.CharField('Comment', max_length=5000)
	posted_on = models.DateField('Posted Date')
	submit_on = models.DateField('Submission Date')

	def __unicode__(self):
		return u' teacher : %s ,Subject : %s , name : %s , posted_on  : %s' % (self.teacher,self.subject,self.name,self.posted_on)		

assignment/forms.py
from myproject.sysadmin.models import *
from django import forms
from myproject.setup.models import *

def sess():
    return currentsession.objects.get(id = 1)
currse = currentsession.objects.get(id = 1)

class assignform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':'10','readonly':'readonly'}),initial=sess())
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=[(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')])
    arm = forms.ChoiceField(label= 'Arm', choices = [(a.arm, a.arm) for a in Arm.objects.all()])
    subject = forms.ChoiceField(label= 'Subject', choices = [(a.subject, a.subject) for a in Subject.objects.all()])
    mydate = forms.CharField(label = "Date",max_length = 280,required = True,widget = forms.TextInput(attrs={'readonly':'readonly'}))

    def __init__(self, *args):
        super(assignform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['arm'].choices = [(a.arm, a.arm) for a in Arm.objects.all()]
        self.fields['subject'].choices = [(a.subject, a.subject) for a in Subject.objects.all()]
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]
        self.fields['mydate'].widget.attrs['class'] = 'loginTxtbox'

assignment/views.py
from myproject.sysadmin.models import *
from myproject.assignment.forms import *
from django.shortcuts import render_to_response, get_object_or_404
from django.http import  Http404, HttpResponseRedirect, HttpResponse
from myproject.assignment.models import *
import datetime
from datetime import date
today=datetime.date.today()

def choose(request):
    if 'userid' in request.session:
        varuser=request.session['userid']
        user=userprofile.objects.get(username=varuser)
        uenter=user.curriculum
        if uenter is False:
            return HttpResponseRedirect('/welcome/')
        return render_to_response('assignment/choose.html',{'varuser':varuser})

    else:
        return HttpResponseRedirect('/login/')

def assignment(request):
    if 'userid' in request.session:
        varuser=request.session['userid']
        user=userprofile.objects.get(username=varuser)
        uenter=user.curriculum
        if uenter is False:
            return HttpResponseRedirect('/welcome/')
        varerr='Class Assignment'
        if request.method =='POST':
            form = assignform(request.POST)

     # handling non-form elements  
     
            assignment= request.POST['assignment']
            comment= request.POST['comment']

            rfile=request.FILES['datafile']

            if rfile is None:

                datafile='ax/sand_and_foam.docx'
            else:
                datafile=request.FILES['datafile']

            if form.is_valid():
                session=form.cleaned_data['session']
                klass=form.cleaned_data['klass']
                arm=form.cleaned_data['arm']
                term=form.cleaned_data['term']
                subject=form.cleaned_data['subject']
                mydate=form.cleaned_data['mydate']
                caldate2 = mydate.split('-')
                transdate = date(int(caldate2[2]),int(caldate2[1]),int(caldate2[0]))

                tblassignment(teacher=varuser,
                    subject=subject,
                    klass=klass,
                    arm=arm,
                    ass_file=datafile,
                    term=term,
                    session=session,
                    posted_on=today,
                    submit_on=transdate,
                    comment=comment,
                    assignment=assignment).save()
                return render_to_response('assignment/success.html',{'form':form,'varuser':varuser})
            else:
                varerr='select appropriate date'
                return render_to_response('assignment/assign.html',{'form':form,'varuser':varuser,'varerr':varerr})

        else:
            form=assignform()
        return render_to_response('assignment/assign.html',{'form':form,'varuser':varuser,'varerr':varerr})

    else:
        return HttpResponseRedirect('/login/')

def studassign(request):
    if 'userid' in request.session:
        return render_to_response('assignment/error.html')
    else:
        return HttpResponseRedirect('/welcome/')
        

assignment/templates/assignment/assign.html
{% extends 'welcome.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<body>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><i class="fa fa-book fa-1x"></i> Class Assignment</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- <div classggg="col-md-4 col-md-offset-4"> -->

                <div class="login-panel panel panel-default">
                    
                    <div class="panel-heading">
                        <h3 class="panel-title">{{varerr}}</h3>
                    </div>
                    <div class="panel-body">
                        <form action = ""  method="post" enctype="multipart/form-data" role="form">
                            <fieldset>
                                <div class="form-group">
                                   <label>Session</label>:&nbsp;{{ form.session}} 
                                </div>
                                <div class="form-group">
                                    <!-- <input class="form-control" placeholder="Username" name="username" type="text" autofocus> -->
                                   <label>Term</label>:&nbsp;{{ form.term }}  
                                </div>
                                <div class="form-group">
                                   <label>Class</label>:&nbsp;{{ form.klass }}  
                                </div>
                                <div class="form-group">
                                   <label>Arm</label>:&nbsp;{{ form.arm }}
                                </div>
                                <div class="form-group">
                                   <label>Subject</label>:&nbsp;{{ form.subject }} 
                                </div>
                                <div class="form-group">                                   
                                    <textarea placeholder='Enter assignment here' name='assignment' class="form-control" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                    <label>Upload assignment (if applicable)</label>
                                    <input name="datafile" type="file" >
                                </div>
                                <div class="form-group">                                   
                                    <textarea placeholder='Add Comments' name='comment' class="form-control" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                  <label>Submission Date:</label>:&nbsp;{{ form.mydate }}
                                </div>
                                 <input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value=" Send ">
                            </fieldset>
                        </form>
                    </div>

                </div>
            <!-- </div> -->
<div></div><div></div><div class="box21">  </div>
</body>
</html>

    <script>
        $(document).ready(function() {
            var pickerOpts = {
                //appendText: "mm/dd/yy",
                //defaultDate: "+5",
                showOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat:"dd-mm-yy"
                //showButtonPanel: true
                // showOn: "button"
            };
            $("#id_mydate").datepicker(pickerOpts);
            // alert("welcome");

            getclass();
            //getarm();
            // getterm();

        });
    </script>

    
   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_subject").change(function () {
                autopost2();
            });
            $("#id_arm").change(function () {
                getsubject();
            });
            $("#id_klass").change(function () {
                getarm();
            });
            $("#id_term").change(function () {
                autopost2();
            });
        });
    </script>

    <script type="text/javascript" language="javascript">
        function getclass(){
            var state = $("#id_session").val();
            //alert(state);
            var url = "/assessment/getclass/";
            var i = 0;
            var data='userid='+state;
            $("#id_klass").val('');   
            $("#id_klass").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_klass").append(options);
                        getarm();

                    }
                })
            }
        }
    </script>
    <script type="text/javascript" language="javascript">
        function getterm(){
            var state = $("#id_session").val() ;
            //alert(state);
            var url = "/assessment/getterm/";
            var i = 0;
            var data='userid='+state;
            $("#id_term").val('');
            $("#id_term").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_term").append(options);
                    }
                })
            }
        }

    </script>
    <script type="text/javascript" language="javascript">
        function getarm(){
            var state = $("#id_session").val() + ':'+ $("#id_klass").val() ;
            //alert(state);
            var url = "/assessment/getarm/";
            var i = 0;
            var data='userid='+state;
            $("#id_arm").val('');
            $("#id_arm").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_arm").append(options);
                        getsubject();
                    }
                })
            }
        }

    </script>

    <script type="text/javascript" language="javascript">
        function getsubject(){
            //var state = $("#id_session").val() ;
            var state = $("#id_session").val() + ':'+ $("#id_klass").val()+':'+ $("#id_arm").val() +':'+ $("#id_term").val();
            var url = "/assessment/getsubject/";
            var i = 0;
            var data='userid='+state;
            $("#id_subject").val('');
            $("#id_subject").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_subject").append(options);
                        autopost2();
                    }
                })
            }
        }

    </script>

    <script type="text/javascript" language="javascript">
        function autopost2(){
            var state = $("#id_session").val() + ':'+ $("#id_klass").val()+':'+ $("#id_arm").val() +':'+ $("#id_term").val()+':'+ $("#id_subject").val() ;
            var url = "/assessment/getassign/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    alert($("#id_klass").val())
                    $(".box21").show();
                    $(".box21").html(html);
                }
            });
            return false;
        }
    </script>
{% endblock %}

assignment/templates/assignment/assignment.html
{% extends 'welcome1.html' %}
{%block content%}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>IGBOBI COLLEGE YABA</title>

</head>

<body>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                           Assignments
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table class="table table-responsive table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>S/N</th>
                                        <th>Subject</th>
                                        <th>Assignment</th>
                                        <th>Comment</th>
                                        <th>Posted Date</th>
                                        <th>Submission Date</th>
                                        <th>File</th>
                                    </tr>
                                </thead>
                                <tbody>

                  {% for student in data %}
                       <tr >
                           <td>{{ forloop.counter }}</td>
                           <td>{{ student.subject }}</td>
                           <td>{{ student.assignment }}</td>
                            <td >{{ student.comment }}</td>
                           <td>{{ student.posted_on }}</td>                          
                           <td>{{ student.submit_on }}</td>
                           {% if student.ass_file %}
                           <td ><a href="/student/search/{{ student.id }}/" style="color:blue;font-weight:bold;font-size:12px;">View Details</a></td>
                           {% else%}
                           <td style='color:blue'>No attached File</a></td>
                           {% endif %}
                       </tr>
                   {% endfor %}
                               <div > <a style='color:blue' href="#">view all assignments</a></div>
                 </tbody>
                </table>

                        </div>

                        <!-- /.panel-body -->
                    </div>

                    <!-- /.panel -->
                </div>

                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->

    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
    </script>

</body>

</html>
{% endblock %}

assignment/templates/assignment/choose.html
{% extends "welcome.html" %}
{% block content %}
<html> 
<head>

</head> 
<body>

            <div class="row">
                <div class="col-lg-12">
              <h1 class="page-header"><i class="fa fa-list fa-1x"></i> Assignment</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
  

            <div class="row">
       
                <a href="/assignment/t/pa/">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-light">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-list fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div>Class Assignment </div>
                                </div>
                            </div>
                        </div>
                  
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                       
                    </div>
                </div>
                 </a>

                <a href="/assignment/s/pj/">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-edit fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div>Group Assignments</div>
                                </div>
                            </div>
                        </div>
                  
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                       
                    </div>
                </div>
                 </a>


            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-8">

                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="row">



                                <div class="col-lg-8">
                                    <div id="morris-bar-chart"></div>
                                </div>
                                <!-- /.col-lg-8 (nested) -->
                            </div>
                            <!-- /.row -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->






                </div>
                <!-- /.col-lg-8 -->
                <div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bell fa-fw"></i> Notifications Panel
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="list-group">
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small"><em>4 minutes ago</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small"><em>12 minutes ago</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small"><em>27 minutes ago</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small"><em>43 minutes ago</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small"><em>11:32 AM</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-bolt fa-fw"></i> Server Crashed!
                                    <span class="pull-right text-muted small"><em>11:13 AM</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-warning fa-fw"></i> Server Not Responding
                                    <span class="pull-right text-muted small"><em>10:57 AM</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-shopping-cart fa-fw"></i> New Order Placed
                                    <span class="pull-right text-muted small"><em>9:49 AM</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-money fa-fw"></i> Payment Received
                                    <span class="pull-right text-muted small"><em>Yesterday</em>
                                    </span>
                                </a>
                            </div>
                            <!-- /.list-group -->
                            <a href="#" class="btn btn-default btn-block">View All Alerts</a>
                        </div>
                        <!-- /.panel-body -->
                    </div>

                    <!-- /.panel -->
                    <div class="chat-panel panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-comments fa-fw"></i> Chat
                            <div class="btn-group pull-right">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                                <ul class="dropdown-menu slidedown">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-refresh fa-fw"></i> Refresh
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-check-circle fa-fw"></i> Available
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-times fa-fw"></i> Busy
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-clock-o fa-fw"></i> Away
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-sign-out fa-fw"></i> Sign Out
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- /.panel-heading -->





                        <div class="panel-footer">
                            <div class="input-group">
                                <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
                                <span class="input-group-btn">
                                    <button class="btn btn-warning btn-sm" id="btn-chat">
                                        Send
                                    </button>
                                </span>
                            </div>
                        </div>
                        <!-- /.panel-footer -->
                    </div>
                    <!-- /.panel .chat-panel -->



                </div>
                <!-- /.col-lg-4 -->
            </div>
            <!-- /.row -->
</body>
</html>
{% endblock %}

assignment/templates/assignment/error.html
{% extends "welcome.html" %}
{% block sectionTitle %}Success{% endblock %}
{% block content %}

            <div class="row">
                <div class="col-lg-12">
              <h1 class="page-header"><i class="fa fa-list fa-1x"></i> Group Assignment</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>


   <i class="fa fa-bolt fa-3x"> </i><span style="font-size:20px;color:black;text-align:center;">Contents not available at the moment, click <a href="/assignment/assignment/">here</a> to continue</span>
{% endblock %}