student/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import DetailView, TemplateView
from myproject.student import models

urlpatterns = patterns('myproject.student.views',
    # Examples:
    url(r'^$', 'index'),
    url(r'^register/$', 'register'),
    url(r'^admno/$', 'getadmno'),
    url(r'^wel/$', 'wel'),
    url(r'^subclass/$', 'getsubclass'),
    url(r'^findstudent/$', 'autocomplete'),
   # url(r'^edit/$', 'edit_registration'),
   # url(r'^withdraw/$', 'withdraw_student'),
   # url(r'^return/$', 'return_withdrawn_student'),
    url(r'^ajaxlga/$', 'getlocal'),
    url(r'^editregistration/$', 'editreg'),
    url(r'^studentinfo/$', 'getstuinfo'),
    url(r'^autopost/$', 'getstuinfoauto'),
    url(r'^studentreport/$', 'studentreport'),
    #url(r'^studentreportpdf/$', 'studentreppdf'),
    url(r'^withdraw_student/$', 'withdrawstudent'),
    url(r'^withdrawajax/$', 'withdrawajax'),
    url(r'^student_return/$', 'returngonestudent'),
    url(r'^studentinfogone/$', 'getstuinfogone'),
    url(r'^returnajax/$', 'returnajax'),
    url(r'^withdrawn_report/$', 'withdrawnreport'),
    url(r'^success/$', 'studentsuccessful'),
    url(r'^search/(\d+)/$', 'searchstudent'),
    url(r'^profile/$', 'searchprofile'),
    url(r'^search_ajax/$', 'studentsearchajax'),
    url(r'^search_ajax1/$', 'studentsearchajax1'),



   # url(r'^report/student/$', TemplateView.as_view(template_name='student/student_report.html')),
    #url(r'^report/student/list/$', 'get_report'),
    #url(r'^report/student/(?P<pk>\d+)/$', DetailView.as_view(template_name='student/student_detail.html', model=models.Student)),
    #url(r'^report/withdrawn/$', TemplateView.as_view(template_name='student/withdrawn_report.html')),
    #url(r'^report/withdrawn/list/$', 'get_report', {'type': 'withdrawn'}),

    #url(r'^find/$', 'autocomplete'),
    #url(r'^find/gone/$', 'autocomplete', {'gone': True}),
    #url(r'^getlga/(?P<state>\w+)/$', 'get_lga_as_list'),

    #url(r'^getform/$', 'edit_registration', {'is_ajax': True}),
    #url(r'^getform/return/$', 'return_withdrawn_student', {'is_ajax': True}),
    #url(r'^getform/withdraw/$', 'withdraw_student', {'is_ajax': True}),

    #url(r'success/$', TemplateView.as_view(template_name='student/success.html')),
)

urls.py
from django.conf.urls.defaults import *
from myproject.signals import *
from django.conf import settings
from myproject.sysadmin.views import *
from myproject.setup.views import *
from myproject.utilities.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', index),studentlogin
    # url(r'^login/$', index),


    url(r'^$', studentlogin),
    url(r'^login/$', studentlogin),

    url(r'^login/admin/$', index),

    url(r'^header/$', header),
    url(r'^welcome/$', welcomecode),
    url(r'^online/$', online_result),
    url(r'^subject_report/$', subject_report),
    url(r'^student_search/$', search_student),
    url(r'^logout/$', logoutuser),
    url(r'^unauthorised/$', unatho),
    url(r'^uploadlga/$',uploadlocal ),
    url(r'^uploadsubgroup/$',uploadaccsubgrp),
    url(r'^uploadacc/$',uploadacc),
    url(r'^home_dashboard/$',dashboard),
    url(r'^uploadtransaction/$',uploadtransaction),
    url(r'^pass_change/$', change_password),
    url(r'^getchangepassword/$', getchangepassword),
    url(r'^uploadstudent/$',uploadstudent),
    url(r'^uploadbill/$',uploadbill),#to upload bill setup
    url(r'^uploadbillname/$',uploadbillname),#to upload bill name
    url(r'^uploadadditionalbill/$',uploadadditionalbill),#to upload  additional bills
    url(r'^uploadpostedbill/$',uploadpostedbill),#to upload posted bill

    url(r'^changepassword/$', changepassword),
    url(r'^setup/', include('myproject.setup.urls')),
    url(r'^student/', include('myproject.student.urls')),
    url(r'^bill/', include('myproject.bill.urls')),
    url(r'^cbt/', include('myproject.CBT.urls')),
    url(r'^sysadmin/', include('myproject.sysadmin.urls')),
    url(r'^controllers/', include('myproject.sysadmin.urls')),
    url(r'^assessment/', include('myproject.assessment.urls')),

    url(r'^lesson/', include('myproject.lesson.urls')),
    url(r'^authen/', include('myproject.authen.urls')),

    url(r'^assignment/', include('myproject.assignment.urls')),
   # url(r'^transport/', include('myproject.transport.urls')),
    url(r'^utils/', include('myproject.utilities.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
   # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),

    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

student/models.py
from django.db import models
from myproject.setup.models import *
from myproject.utils import PhoneNumberValidator, SchoolSessionValidator

# Create your models here.
terms_list = (('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term'))

states = [(state, state) for state in sorted(['Abia', 'Federal Capital Territory', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
              'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Gombe', 'Imo',
              'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nassarawa',
              'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe',
              'Zamfara','Non-Nigeria'])]


class Student(models.Model):
    firstname = models.CharField('First Name', max_length=75)
    surname = models.CharField('Surname', max_length=75)
    othername = models.CharField('Other Names', max_length=75, null=True, blank=True)
    address = models.CharField('Address', max_length=200)
    sex = models.CharField('Sex',max_length=10, choices=(('Male', 'Male'),('Female', 'Female')))
    birth_date = models.DateField('Date of Birth',null=True,blank=True,default='2000-01-01')
    birth_place = models.CharField('Place of Birth', max_length=75)
    state_of_origin = models.CharField('State of Origin', max_length=75, choices=states)
    lga = models.CharField('L.G.A.', max_length=75)
    studentpicture = models.ImageField('Passport', upload_to='studentpix', null=True,blank=True,default='studentpix/user.png')
    fathername = models.CharField("Name", max_length=275)
    fatheraddress = models.CharField('Address', max_length=200)
    fathernumber = models.CharField('Phone Number', max_length=35, null=True,blank=True )#validators=[PhoneNumberValidator]s
    fatheroccupation = models.CharField('Occupation', max_length=175)
    fatheremail = models.CharField('Father E-mail', max_length=200,null=True,blank=True)
    prev_school = models.CharField('Former School', max_length=200, null=True, blank=True)
    prev_class = models.CharField('Former Class', max_length=25, null=True, blank=True)
    admitted_class = models.CharField('Admitted Class', max_length=25)
    admitted_arm = models.CharField('Arm', max_length=25)
    admitted_session = models.CharField('Session Admitted', max_length=25, null=True, blank=True, validators=[SchoolSessionValidator])
    fullname = models.CharField('Full Name', max_length=100, editable=False)
    admissionno = models.CharField('Admission Number', max_length=25)
    house = models.CharField('House', max_length=75 )
    dayboarding = models.CharField('Day/Boarding', max_length=25, choices=(('Day', 'Day'), ('Boarding', 'Boarding')))
    gone = models.BooleanField('Gone', default=False, editable=True)
    userid = models.CharField('User Id',max_length=200,editable=False)
    subclass = models.CharField('Sub Class Admitted', max_length=25)
    first_term = models.BooleanField('First Term', default=False, editable=True, )
    second_term = models.BooleanField('Second Term', default=False, editable=True )
    third_term = models.BooleanField('Third Term', default=False, editable=True )
    def get_full_name(self):
        if self.othername:
            fullname = "%s %s %s" % (self.surname,self.firstname, self.othername)
        else: fullname = "%s %s" % (self.surname,self.firstname)
        return fullname.upper()
    def get_image_url(self):
        illegal_chars = [';', '.', ':', '/', '?', '<', '>', ',', "'", '"', '\\',
                         '{', '}', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')',
                         '_', '+', '=', '-']
        url = self.admissionno
        for char in illegal_chars:
            url = url.replace(char, '')
        return url
    def __unicode__(self):
        return u'%s %s %s %s %s %s'%(self.get_full_name(),self.admissionno,self.admitted_class,self.admitted_arm,self.admitted_session,self.gone)
    class Meta:
        ordering = ['fullname']
        verbose_name_plural = 'Student Information'

    #def save(self, **kwargs):
      #  self.fullname = self.get_full_name()
       # super(Student, self).save(**kwargs)

    def save(self, size=(100, 100), **kwargs):
        """
	Save Photo after ensuring it is not blank. Resize as needed.
	"""
        self.fullname = self.get_full_name()

        if not self.id and not self.studentpicture:
            return

        super(Student, self).save(**kwargs)

        filename = self.studentpicture.path
        image = Image.open(filename)

        image.thumbnail(size, Image.ANTIALIAS)
        image.save(filename)

    class Meta:
        ordering = ['fullname']
        verbose_name_plural = 'Student Information'



class WithdrawnStudent(models.Model):
    student = models.CharField("Student Full Name",max_length=300)
    klass = models.CharField("Student Class",max_length=15)
    arm = models.CharField("Arm",max_length=25)
    admissionno = models.CharField("Admission Number",max_length= 25)
    reason = models.TextField('Reason for Withdrawal')
    date_withdrawn = models.DateField('Date of Withdrawal')
    admitted_session = models.CharField('Withdrwal Session',max_length=15)
    userid = models.CharField("User Id",max_length= 250)

    def __unicode__(self):
        return u'%s - %s - %s - %s' %(self.admissionno,self.student,self.reason,self.userid)

bill/forms.py
from django import forms
from myproject.setup.models import *
from myproject.bill.models import *
from myproject.sysadmin.models import *
from myproject.student.models import *

def sessi():
    if billsession.objects.all().count() == 0:
       currse = currentsession.objects.get(id = 1)
    else:
       currse = billsession.objects.get(id = 1)
    return currse

class expensesForm(forms.Form):
    expenses = forms.CharField(label="Bill Name",max_length= 150,widget=forms.TextInput(attrs={'size':'35'}))

class billForm(forms.Form):
    klass = forms.ChoiceField(label= 'Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    desc = forms.ChoiceField(label= 'Bill Description',choices = [(c.name, c.name) for c in tblexpenses.objects.all()])
    billamount = forms.DecimalField( label='Bill Amount',decimal_places= 2,required=True,max_digits= 15)
    acccode = forms.CharField(label='G/L Account Code',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':35}))
    dayboarding = forms.ChoiceField(label='Day/Boarding',choices= (('Day', 'Day'), ('Boarding', 'Boarding')))
    term = forms.ChoiceField(label='Term',choices=[(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')])
   # term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    def __init__(self, *args):
        super(billForm, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['desc'].choices = [(c.name, c.name) for c in tblexpenses.objects.all()]
        self.fields['desc'].initial = tblexpenses.objects.all()
        self.fields['acccode'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]

class additionalbillform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':10}),initial=sessi)
    admissionno = forms.CharField(label='Admission Number',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':15,'readonly':'readonly'}))
    name = forms.CharField(label='Student Name',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':35}))
    klass = forms.CharField(label='Class',max_length= 20,required=True,widget= forms.TextInput(attrs ={'size':10,'readonly':'readonly'}))
    arm = forms.CharField(label='Arm',max_length= 20,required=True,widget= forms.TextInput(attrs ={'size':10,'readonly':'readonly'}))
    term = forms.ChoiceField(label='Term',choices=[(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')])
    #term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    billamount = forms.DecimalField( label='Bill Amount',decimal_places= 2,required=True,max_digits= 15)
    desc = forms.ChoiceField(label= 'Bill Description',choices = [(c.name, c.name) for c in tblexpenses.objects.all()])
    acccode = forms.CharField(label='G/L Account Code',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':35}))

    def __init__(self, *args):
        super(additionalbillform, self).__init__(*args)
        self.fields['desc'].choices = [(c.name, c.name) for c in tblexpenses.objects.all()]
        self.fields['desc'].initial = tblexpenses.objects.all()
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['admissionno'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['name'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['billamount'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['acccode'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]

class printbillform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':10}),initial=sessi)
    name = forms.ChoiceField(label='Student Name',choices = [(c.fullname, c.fullname) for c in Student.objects.all()])
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    excelfile = forms.BooleanField(label='By Class',required=False)
    pdffile = forms.BooleanField(label='PDF',required=False)

    def __init__(self, *args):
        super(printbillform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['name'].choices = [(c.fullname, c.fullname) for c in Student.objects.all()]
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]

class billscheduleform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':10}),initial=sessi)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    def __init__(self, *args):
        super(billscheduleform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]

class printoldbillform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':10}),initial=sessi)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    studentname = forms.ChoiceField(choices = [(c.fullname, c.fullname) for c in Student.objects.all()], label="Student's Name")
    def __init__(self, *args):
        super(printoldbillform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['studentname'].choices = [(c.fullname, c.fullname) for c in Student.objects.all()]
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'

student/templates/student/edit_reg.html
{% extends 'student/base.htm' %}
{% block sectionTitle %}Edit Registration{% endblock %}
{% block content %}

    <table width="100%" class="table  table-bordered" id="dataTables-example">
        <tr>
            <td d colspan="10" style="text-align:center;color:blue;background-color: #ffffff;font-size:14px;">Edit Student Information </td>
        </tr>
         <tr>
             <td> {{ varerr }}</td>
         </tr>
   </table> 
 <table width="100%" class="table  table-bordered" id="dataTables-example">
        <tr >
            <td>
                {{ searchform.admitted_class1.label_tag }}:{{ searchform.admitted_class1 }}
            </td>

            <td>
                {{ searchform.admitted_arm1.label_tag }}:{{ searchform.admitted_arm1 }}
            </td>

            <td>
                {{ searchform.studentname.label_tag }}
            </td>
            <td>
                {{ searchform.studentname }}
            </td>
        </tr>
   </table> 
 <table width="100%" class="table  table-bordered" id="dataTables-example">
        <tr>
            <td ><div class="box2"></div></td>
        </tr>
  </table>

    <script>
        $(document).ready(function() {
            var pickerOpts = {
                //appendText: "mm/dd/yy",
                //defaultDate: "+5",
                showOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat:"yy-mm-dd"
                //showButtonPanel: true
                // showOn: "button"
            };
            getstudents();
                  });
    </script>

    <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_admitted_class1").change(function () {
                getstudents();
            });
            $("#id_admitted_arm1").change(function () {
                getstudents();
            });
            $("#id_studentname").change(function () {
                autopost2();
            });
        });
    </script>
   
    <script type="text/javascript" language="javascript">
        function getstudents(){
            var state = $("#id_admitted_class1").val() + '-'+ $("#id_admitted_arm1").val();
            //alert(state);
            var url = "/student/studentinfo/";
            var i = 0;
            var data='userid='+state;
            $("#id_studentname").val('');
            $("#id_studentname").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_studentname").append(options);
                        autopost2();
                    }

                })
            }
        }

    </script>
 <script type="text/javascript" language="javascript">
        function autopost2(){
            var state = $("#id_admitted_class1").val() + ':'+ $("#id_admitted_arm1").val()+':'+ $("#id_studentname").val() ;
           // alert(state);
            var url = "/student/autopost/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    $(".box2").show();
                    $(".box2").html(html);
                }
            });
            //alert("error");
            return false;
        }
    </script>
{% endblock %}

student/templates/student/regform1.html
{%  load humanize %}

<form id="form1" action="/student/withdraw_student/" method="post" enctype="multipart/form-data" onsubmit="disable(this)">

<table style="text-align: left; vertical-align: text-top;" >

    <tr >
        <td colspan="4"  style="background-color: #ccccc0;color:black;text-align:center;" >BIO DATA</td>
    </tr>
    <tr>
        <td><label for="id_surname">Surname</label></td>
        <td><input id="id_surname" type="text" name="surname" maxlength="75" value="{{ data.surname }}" readonly="readonly" class="loginTxtbox"/></td>
        <td><label for="id_firstname">First Name</label></td>
        <td><input id="id_firstname" type="text" name="firstname" maxlength="75" value="{{ data.firstname }}" readonly="readonly" class="loginTxtbox"/></td>
        <td rowspan =5><img style = "border:1px solid black;width:100px;height:100px" src ="/static/{{data.studentpicture}}" > </td>
    </tr>
    <tr>
        <td><label for="id_othername">Other Names</label></td>
        <td><input id="id_othername" type="text" name="othername" maxlength="75" value="{{ data.othername }}" readonly="readonly" class="loginTxtbox"/></td>
        <td><label for="id_address">Address</label></td>
        <td><input id="id_address" maxlength="300" name="address" readonly="readonly" value="{{ data.address }}" class="loginTxtbox"/> </td>
    </tr>
    <tr>
        <td><label for="id_sex">Sex</label></td>
        <td><input id="id_sex" maxlength="10" name="sex" readonly="readonly" value="{{ data.sex }}" class="loginTxtbox"/> </td>
        <td><label for="id_birth_date">Date Of Birth</label></td>
        <td><input id="id_birth_date" readonly="readonly" type="text" name="birth_date" maxlength="12" value="{{ data.birth_date|date:'d/m/Y' }}" class="loginTxtbox"/></td>
    </tr>
    <tr>
        <td><label for="id_birth_place">Place of Birth</label></td>
        <td><input id="id_birth_place" type="text" name="birth_place" maxlength="75"  value="{{ data.birth_place }}" readonly="readonly" class="loginTxtbox"/></td>
        <td><label for="id_state_of_origin">State of Origin</label></td>
        <td><input id="id_state_of_origin" maxlength="300" name="state_of_origin" readonly="readonly" value="{{ data.state_of_origin }}" class="loginTxtbox"/> </td>
    </tr>
    <tr>
        <td><label for="id_lga">L.G.A.</label></td>
        <td><input id="id_lga" maxlength="300" name="lga" readonly="readonly" value="{{ data.lga }}" class="loginTxtbox"/> </td>
        <!-- <td><label for="id_studentpicture">Studentpicture</label></td>
  <td><input id="id_studentpicture" type="file" name="studentpicture" size="5" />&nbsp;</td> -->
        <td><label for="id_admissionno">Admission Number</label></td>
        <td><input id="id_admissionno" type="text" name="admissionno" maxlength="25"  readonly="readonly" value="{{ data.admissionno }}" class="loginTxtbox"/></td>
    </tr>
    <tr>
        <td colspan="4"  style="background-color: #ccccc0;color:black;text-align:center;"> Reason For Withdrawal</td>
    </tr>
    <tr>
        <td><label for="id_reason">Reason</label></td>
        <td><textarea id="id_reason" rows="4" cols="20" name="reason"></textarea> </td>
        <td><label for="id_datewithdrawal">Date Withdrwal</label></td>
        <td><input id="id_datewithdrawal" readonly="readonly" type="text" name="datewithdrawal" maxlength="12" class="loginTxtbox"/></td>
    </tr>
       <tr>
        <td colspan="4" style="text-align: center; vertical-align: middle;"><input name="submit" type="submit" value=":: Withdraw Student ::"></td>
    </tr>
    <tr>

        <td><input id="id_admissionnoold" type="hidden" name="admissionnoold" maxlength="25"  value="{{ data.admissionno }}" class="loginTxtbox"/></td>
        <td><input id="id_oldclass" type="hidden" name="oldclass" maxlength="25"  value="{{ data.admitted_class }}" class="loginTxtbox"/></td>
    </tr>
</table>
    <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing';
            button.disabled = 'true';
            return true;
        }
    </script>
<script>
    $(document).ready(function() {
        var pickerOpts = {
            //appendText: "mm/dd/yy",
            //defaultDate: "+5",
            showOtherMonths: true,
            changeMonth: true,
            changeYear: true,
            dateFormat:"yy-mm-dd"
            //showButtonPanel: true
            // showOn: "button"
        };
        $("#id_datewithdrawal").datepicker(pickerOpts);
        //$("#id_dateofresum").datepicker(pickerOpts);
        $("#id_reason").focus();
        //$("id_birth_date").attr('disable','True');

        // getLGAs();
        // subclass()

    });
</script>
</form>

student/templates/student/student_detail.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

student/templates/student/student_report.html
<table style="width: 100%">


    <tr>
        <td style="width:auto; text-align: right; vertical-align: middle;">
            <img style="width: 120px; height: 120px;" src="/static/{{ school.logo }}" alt="{{ school.name }}">
        </td>
        <td style="width:auto; text-align: left;">
            <span style="font-size:18px;font-weight:bold;">{{ school.name }}</span><br>
            {{ school.address }}<br>
            {{ school.website }}

        </td>
    </tr>
    <tr>

        <td style="text-align:center;width:100%;" colspan="8"><h2>{{ disclass }}&nbsp;{{ disarm }} Student List for </h2> <h3>{{ session }} Session</h3></td>

    </tr>
    <tr style="border-bottom:solid #000000">
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">S/N</td>
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">Name</td>
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">Sex</td>
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">Admission No</td>
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">Class</td>
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">Arm</td>
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">House</td>
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">Day/Boarding</td>
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">Phone Number</td>
        <td style="font-weight: bold; background-color: #008b8b; text-align:left;color:white;">E-Mail</td>
    </tr>

    {% for student in students_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ student.fullname }}</td>
            <td>{{ student.sex }}</td>
            <td>{{ student.admissionno }}</td>
            <td>{{ student.admitted_class }}</td>
            <td>{{ student.admitted_arm }}</td>
            <td>{{ student.house }}</td>
            <td>{{ student.dayboarding }}</td>
            <td>{{ student.fathernumber }}</td>
            <td>{{ student.fatheremail }}</td>
        </tr>
    {% endfor %}

</table>