bill/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('myproject.bill.views',
    # Examples:
    url(r'^billname/$', 'addexpensesname'),
    url(r'^wel/$', 'wel'),
    url(r'^deleteexpense/(\d+)/$', 'deleteexpensesname'),
    url(r'^billsetup/$', 'billsetup'),
    url(r'^setupajax/$', 'billsetupajax'),
    url(r'^deletebillajax/(\d+)/$', 'deletebillajax'),
    url(r'^additionalbill/$', 'additionalbill'),
    url(r'^findstudent/$', 'autocomplete'),
    url(r'^addajax/$', 'billaddsetupajax'),
    url(r'^deleteaddbill/(\d+)/$', 'deleteaddbillajax'),
    url(r'^printbill/$', 'printbill'),
    url(r'^getstudent/$', 'getstuinfoajax'),
    url(r'^billschedule/$', 'printbillschdule'),
    url(r'^findacc/$', 'autocompletenameacc'),
    url(r'^printoldbill/$', 'printoldbill'),
    url(r'^getbill/$', 'genbill'),
    url(r'^update_calendar/$', 'bill_calendar_update'),
    url(r'^repoint-account/$', 'repoint_account'),#to convert our liabilities account to Income Account

    )

urls.py
from django.conf.urls.defaults import *
from myproject.signals import *
from django.conf import settings
from myproject.sysadmin.views import *
from myproject.setup.views import *
from myproject.utilities.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', index),studentlogin
    # url(r'^login/$', index),


    url(r'^$', studentlogin),
    url(r'^login/$', studentlogin),

    url(r'^login/admin/$', index),

    url(r'^header/$', header),
    url(r'^welcome/$', welcomecode),
    url(r'^online/$', online_result),
    url(r'^subject_report/$', subject_report),
    url(r'^student_search/$', search_student),
    url(r'^logout/$', logoutuser),
    url(r'^unauthorised/$', unatho),
    url(r'^uploadlga/$',uploadlocal ),
    url(r'^uploadsubgroup/$',uploadaccsubgrp),
    url(r'^uploadacc/$',uploadacc),
    url(r'^home_dashboard/$',dashboard),
    url(r'^uploadtransaction/$',uploadtransaction),
    url(r'^pass_change/$', change_password),
    url(r'^getchangepassword/$', getchangepassword),
    url(r'^uploadstudent/$',uploadstudent),
    url(r'^uploadbill/$',uploadbill),#to upload bill setup
    url(r'^uploadbillname/$',uploadbillname),#to upload bill name
    url(r'^uploadadditionalbill/$',uploadadditionalbill),#to upload  additional bills
    url(r'^uploadpostedbill/$',uploadpostedbill),#to upload posted bill

    url(r'^changepassword/$', changepassword),
    url(r'^setup/', include('myproject.setup.urls')),
    url(r'^student/', include('myproject.student.urls')),
    url(r'^bill/', include('myproject.bill.urls')),
    url(r'^cbt/', include('myproject.CBT.urls')),
    url(r'^sysadmin/', include('myproject.sysadmin.urls')),
    url(r'^controllers/', include('myproject.sysadmin.urls')),
    url(r'^assessment/', include('myproject.assessment.urls')),

    url(r'^lesson/', include('myproject.lesson.urls')),
    url(r'^authen/', include('myproject.authen.urls')),

    url(r'^assignment/', include('myproject.assignment.urls')),
   # url(r'^transport/', include('myproject.transport.urls')),
    url(r'^utils/', include('myproject.utilities.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
   # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),

    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

bill/models.py
from django.db import models

# Create your models here.
class tblexpenses(models.Model):
    name = models.CharField('name', max_length=160)

    def __unicode__(self):
        return  u'%s' % self.name


    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Bill Creation'

class tblbill(models.Model):
    klass = models.CharField(max_length= 130)
    desc = models.CharField(max_length= 300)
    billamount = models.DecimalField(decimal_places=2,max_length=65,max_digits=65)
    acccode = models.CharField(max_length= 300)
    dayboarding = models.CharField(max_length= 50)
    term = models.CharField(max_length= 50)
    userid = models.CharField(max_length= 150)
    def __unicode__(self):
        return  u'%s - %s - %s - %s - %s - %s - %s' % (self.klass,self.desc,self.billamount,self.acccode,self.dayboarding,self.term,self.userid)
    class Meta:
        ordering = ['klass','id']
        verbose_name_plural = 'Bill SetUp'

class tbladditionalbill(models.Model):
    session = models.CharField(max_length= 130)
    admissionno = models.CharField(max_length= 130)
    name = models.CharField(max_length= 230)
    klass = models.CharField(max_length= 130)
    arm = models.CharField(max_length= 130)
    term = models.CharField(max_length= 130)
    billamount = models.DecimalField(decimal_places=2,max_length=65,max_digits=65)
    desc = models.CharField(max_length= 130)
    acccode = models.CharField(max_length= 130)
    userid = models.CharField(max_length= 150)

    def __unicode__(self):
        return  u'%s - %s - %s - %s - %s - %s - %s -%s -%s' % (self.session,self.admissionno,self.name,self.klass,self.arm,self.term,self.billamount,self.acccode,self.desc)

    class Meta:
        ordering = ['klass','id']
        verbose_name_plural = 'Additional Bill'

class postedbill(models.Model):
    session = models.CharField(max_length= 130)
    klass = models.CharField(max_length= 130)
    term = models.CharField(max_length= 130)
    userid = models.CharField(max_length= 150)
    dateposted = models.DateTimeField(auto_now_add=True, blank=True)
    def __unicode__(self):
        return  u'%s - %s - %s - %s -%s' % (self.session,self.klass,self.term,self.userid,self.dateposted)

    class Meta:
        ordering = ['klass','id']
        verbose_name_plural = 'Posted Bill'

class oldbill(models.Model):
    session = models.CharField(max_length= 130)
    admissionno = models.CharField(max_length= 130)
    name = models.CharField(max_length= 230)
    klass = models.CharField(max_length= 130)
    arm = models.CharField(max_length= 130)
    term = models.CharField(max_length= 130)
    billamount = models.DecimalField(decimal_places=2,max_length=65,max_digits=65)
    desc = models.CharField(max_length= 130)
    acccode = models.CharField(max_length= 130)
    userid = models.CharField(max_length= 150)
    def __unicode__(self):
        return  u'%s - %s - %s - %s - %s - %s - %s -%s -%s' % (self.session,self.admissionno,self.name,self.klass,self.arm,self.term,self.billamount,self.acccode,self.desc)

    class Meta:
        ordering = ['admissionno','id']
        verbose_name_plural = 'Old Bill'

class billsession(models.Model):
    session = models.CharField('Current Session',max_length= 25)

    def __unicode__(self):
        return "%s" %self.session
    class Meta:
        ordering = ['id']
        verbose_name_plural = 'Bill Calendar Year'

bill/forms.py
from django import forms
from myproject.setup.models import *
from myproject.bill.models import *
from myproject.sysadmin.models import *
from myproject.student.models import *

def sessi():
    if billsession.objects.all().count() == 0:
       currse = currentsession.objects.get(id = 1)
    else:
       currse = billsession.objects.get(id = 1)
    return currse

class expensesForm(forms.Form):
    expenses = forms.CharField(label="Bill Name",max_length= 150,widget=forms.TextInput(attrs={'size':'35'}))

class billForm(forms.Form):
    klass = forms.ChoiceField(label= 'Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    desc = forms.ChoiceField(label= 'Bill Description',choices = [(c.name, c.name) for c in tblexpenses.objects.all()])
    billamount = forms.DecimalField( label='Bill Amount',decimal_places= 2,required=True,max_digits= 15)
    acccode = forms.CharField(label='G/L Account Code',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':35}))
    dayboarding = forms.ChoiceField(label='Day/Boarding',choices= (('Day', 'Day'), ('Boarding', 'Boarding')))
    term = forms.ChoiceField(label='Term',choices=[(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')])
   # term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    def __init__(self, *args):
        super(billForm, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['desc'].choices = [(c.name, c.name) for c in tblexpenses.objects.all()]
        self.fields['desc'].initial = tblexpenses.objects.all()
        self.fields['acccode'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]

class additionalbillform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':10}),initial=sessi)
    admissionno = forms.CharField(label='Admission Number',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':15,'readonly':'readonly'}))
    name = forms.CharField(label='Student Name',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':35}))
    klass = forms.CharField(label='Class',max_length= 20,required=True,widget= forms.TextInput(attrs ={'size':10,'readonly':'readonly'}))
    arm = forms.CharField(label='Arm',max_length= 20,required=True,widget= forms.TextInput(attrs ={'size':10,'readonly':'readonly'}))
    term = forms.ChoiceField(label='Term',choices=[(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')])
    #term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    billamount = forms.DecimalField( label='Bill Amount',decimal_places= 2,required=True,max_digits= 15)
    desc = forms.ChoiceField(label= 'Bill Description',choices = [(c.name, c.name) for c in tblexpenses.objects.all()])
    acccode = forms.CharField(label='G/L Account Code',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':35}))

    def __init__(self, *args):
        super(additionalbillform, self).__init__(*args)
        self.fields['desc'].choices = [(c.name, c.name) for c in tblexpenses.objects.all()]
        self.fields['desc'].initial = tblexpenses.objects.all()
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['admissionno'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['name'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['billamount'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['acccode'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]

class printbillform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':10}),initial=sessi)
    name = forms.ChoiceField(label='Student Name',choices = [(c.fullname, c.fullname) for c in Student.objects.all()])
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    excelfile = forms.BooleanField(label='By Class',required=False)
    pdffile = forms.BooleanField(label='PDF',required=False)

    def __init__(self, *args):
        super(printbillform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['name'].choices = [(c.fullname, c.fullname) for c in Student.objects.all()]
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]

class billscheduleform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':10}),initial=sessi)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    def __init__(self, *args):
        super(billscheduleform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'
        self.fields['term'].choices = [(a.term, a.term) for a in tblterm.objects.filter(status = 'ACTIVE')]

class printoldbillform(forms.Form):
    session = forms.CharField(label='Session',max_length= 190,required=True,widget= forms.TextInput(attrs ={'size':10}),initial=sessi)
    klass = forms.ChoiceField(label='Class',choices = [(c.klass, c.klass) for c in Class.objects.all()])
    term = forms.ChoiceField(label='Term',choices=(('First', 'First'), ('Second', 'Second'), ('Third', 'Third')))
    studentname = forms.ChoiceField(choices = [(c.fullname, c.fullname) for c in Student.objects.all()], label="Student's Name")
    def __init__(self, *args):
        super(printoldbillform, self).__init__(*args)
        self.fields['klass'].choices = [(c.klass, c.klass) for c in Class.objects.all()]
        self.fields['klass'].initial = Class.objects.all()
        self.fields['studentname'].choices = [(c.fullname, c.fullname) for c in Student.objects.all()]
        self.fields['session'].widget.attrs['class'] = 'loginTxtbox'

bill/templates/bill/addbill.html
{% extends 'bill/base.htm' %}
{% block sectionTitle %}Student Registration{% endblock %}
{% block content %}
    <table style="width:100%">
        <tr>
            <td colspan="10">
                <form id="form1" action="" method="post" enctype="multipart/form-data" onsubmit="disable(this)">
                    <table style="width:auto;text-align: left; vertical-align: text-top; border: 0px;" >
                        <tr>
                            <td colspan="10" style="text-align:center;color:black;background-color:#ccccc0;font-size:14px;font-weight:bd;">ADDITIONAL BILL MENU</td>
                        </tr>
                        <tr>
                            <td style="text-align:left;color:#cc000f;font-size:14px;">Student Information</td>
                        </tr >
                        <tr >
                            <td colspan="4"  style="background-color:#d3d3d3;font-size:13px;color:red;font-weight:bold;text-decoration:blink;text-align:center" > {{ varerr }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.name.label_tag }}</td>
                            <td>{{ form.name }}&nbsp;{{ form.name.errors }}</td>
                            <td>{{ form.admissionno.label_tag }}</td>
                            <td>{{ form.admissionno }}&nbsp;{{ form.admissionno.errors }}</td>
                        </tr>
                        <tr>

                            <td>{{ form.klass.label_tag }}</td>
                            <td>{{ form.klass }}&nbsp;{{ form.klass.errors }}</td>
                            <td>{{ form.arm.label_tag }}</td>
                            <td>{{ form.arm }}&nbsp;{{ form.arm.errors }}</td>
                        </tr>
                        <tr>
                            <td colspan="10" style="text-align:center;color:black;background-color:#ccccc0;font-size:14px;font-weight:bd;">
                                 ADDITIONAL BILL SETUP
                            </td>
                        <tr>
                            <td>{{ form.term.label_tag }}</td>
                            <td>{{ form.term }}&nbsp;{{ form.term.errors }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.desc.label_tag }}</td>
                            <td>{{ form.desc }}&nbsp;{{ form.desc.errors }}</td>
                            <td>{{ form.billamount.label_tag }}</td>
                            <td>{{ form.billamount }}&nbsp;{{ form.billamount.errors }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.acccode.label_tag }}</td>
                            <td>{{ form.acccode }}&nbsp;{{ form.acccode.errors }}</td>

                            <td>{{ form.session.label_tag }}</td>
                            <td>{{ form.session }}&nbsp;{{ form.session.errors }}</td>
                        </tr>
                        <tr>
                            <td colspan="4" style="text-align: center; vertical-align: middle;"><input type="submit" value=":: Submit BILL ::" name="submit"></td>
                            <td></td>
                        </tr>
                    </table>
                </form>

            </td>
        </tr>
        <tr>
            <td colspan="10"><div class="box"></div></td>
        </tr>
    </table>

    <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing';
            button.disabled = 'true';
            return true;
        }
    </script>
    <script>
        $(document).ready(function() {
            var pickerOpts = {
                //appendText: "mm/dd/yy",
                //defaultDate: "+5",
                showOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat:"yy-mm-dd"
                //showButtonPanel: true
                // showOn: "button"
            };
            // autopost();
            $("#id_session").keyup(function () {
                autopostbill();
            });

            $("#id_term").change(function () {
                autopostbill();
            });
            $("#id_name").keyup(function() {
                $("#id_admissionno").val("");
                $("#id_klass").val("");
                $("#id_arm").val("");

            });
            $( "#id_name" ).focus();
            autocomplete();
            autocompleteacc();
        });
    </script>
    <script type="text/javascript" language="javascript">
        function autopostbill(){
            var state = $("#id_admissionno").val() + ':'+ $("#id_session").val() + ':'+ $("#id_term").val();
            //alert(state);
            var url = "/bill/addajax/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    $(".billbox").show();
                    $(".billbox").html(html);
                }
            });
            //alert("error");
            return false;


        }
    </script>

    <script type="text/javascript" language="javascript">
        function autocomplete(){
            $("#id_name").autocomplete({
                source: "/bill/findstudent/",
                select: function( event, ui ) {
                    $( "#id_name" ).val( ui.item.name );
                    $( "#id_admissionno" ).val( ui.item.admno );
                    $( "#id_klass" ).val( ui.item.klass );
                    $( "#id_arm" ).val( ui.item.arm );
                    autopostbill();
                    return false;
                }
            })
                    .data( "autocomplete" )._renderItem = function( ul, item ) {
                return $( "<li></li>" )
                        .data( "item.autocomplete", item )
                        .append( "<a>" + item.label + "</a>" )
                        .appendTo( ul );
            };

        }

    </script>

    <script type="text/javascript" language="javascript">
        function autocompleteacc(){
            // var sess =  $( "#id_session" ).val();
            //alert(sess);
            $("#id_acccode").autocomplete({
                //minLength: 0
                // var sess =  $( "#id_name" ).val();
                source: "/bill/findacc/",

                //source: "/bill/findstudent/"+ $( "#id_session" ).val() + "/",
                //focus: function(event, ui){
                  //  $("#id_acccode").val(ui.item.acccode);
                    //$( "#id_staffname" ).val( ui.item.label.name );
                    // populateForm(ui.item.value);
                    //return false;
                //},
                select: function( event, ui ) {
                    $( "#id_acccode" ).val( ui.item.acccode );
                    return false;
                }
            })
                    .data( "autocomplete" )._renderItem = function( ul, item ) {
                return $( "<li></li>" )
                        .data( "item.autocomplete", item )
                        .append( "<a>" + item.label + "</a>" )
                        .appendTo( ul );
            };
        }

    </script>
    <script type="text/javascript">
        function disbutton(){
            $("input[type=submit]").attr("disabled", "disabled");
            return false;
        }
    </script>
{% endblock %}

bill/templates/bill/bill.html
{% extends 'bill/base.htm' %}
{% block sectionTitle %}{% endblock %}
{% block content %}
    <table style="width:100%">
    <tr>
        <td colspan="10">
             <form id="form1" action="" method="post" enctype="multipart/form-data" onsubmit="disable(this)">
                        <table style="width:auto;text-align:left; vertical-align:text-top; border:0px;" >
                            <tr>
                                <td colspan="10" style="text-align:center;color:white;background-color: #ccccc0;font-size:14px;color:black;">Bill Setup</td>
                            </tr>
                            <tr >
                                <td colspan="4"  style="background-color:#d3d3d3;font-size:13px;color:red;font-weight:bold;text-decoration:blink;text-align:center" > {{ varerr }}</td>
                            </tr>
                            <tr>
                                <td>{{ form.klass.label_tag }}</td>
                                <td>{{ form.klass }}&nbsp;{{ form.klass.errors }}</td>
                                <td>{{ form.term.label_tag }}</td>
                                <td>{{ form.term }}&nbsp;{{ form.term.errors }}</td>
                            </tr>

                            <tr>
                                <td>{{ form.desc.label_tag }}</td>
                                <td>{{ form.desc }}&nbsp;{{ form.desc.errors }}</td>
                                <td>{{ form.billamount.label_tag }}</td>
                                <td>{{ form.billamount }}&nbsp;{{ form.billamount.errors }}</td>

                            </tr>
                            <tr>
                                <td>{{ form.acccode.label_tag }}</td>
                                <td>{{ form.acccode }}&nbsp;{{ form.acccode.errors }}</td>
                                <td>{{ form.dayboarding.label_tag }}</td>
                                <td>{{ form.dayboarding }}&nbsp;{{ form.dayboarding.errors }}</td>

                            </tr>

                            <tr>
                                <td colspan="4" style="text-align: center; vertical-align: middle;"><input type="submit" value=":: Create BILL ::" name="submit"></td>
                                <td></td>
                            </tr>
                        </table>
                    </form>

        </td>
    </tr>
        <tr>

            <td colspan="10">
                <div class="box">
                </div>
            </td>
        </tr>
    </table>

    <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing... pls wait';
            button.disabled = 'true';
            return true;
        }
    </script>
    <script>
        $(document).ready(function() {
            var pickerOpts = {
                //appendText: "mm/dd/yy",
                //defaultDate: "+5",
                showOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat:"yy-mm-dd"
                //showButtonPanel: true
                // showOn: "button"
            };
            autopostbill();
            $("#id_klass").change(function () {
                autopostbill();
            });
            $("#id_term").change(function () {
                autopostbill();
            });
            $("#id_dayboarding").change(function () {
                autopostbill();
            });

            $( "#id_billamount" ).focus();
            autocomplete();
        });
    </script>

    
    <script type="text/javascript" language="javascript">
    
        function autopostbill(){
            var state = $("#id_klass").val() + ':'+ $("#id_term").val()+':'+ $("#id_dayboarding").val() ;
            var url = "/bill/setupajax/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    $(".billbox").show();
                    $(".billbox").html(html);
                }
            });
            //alert("error");
            return false;
        }
    </script>
    <script type="text/javascript" language="javascript">
        function autocomplete(){
            $("#id_acccode").autocomplete({
                source: "/bill/findacc/",
                select: function( event, ui ) {
                    $( "#id_acccode" ).val( ui.item.acccode );
                    return false;
                }
            })
                    .data( "autocomplete" )._renderItem = function( ul, item ) {
                return $( "<li></li>" )
                        .data( "item.autocomplete", item )
                        .append( "<a>" + item.label + "</a>" )
                        .appendTo( ul );
            };

        }
    </script>
    <script type="text/javascript">
        function disbutton(){
            $("input[type=submit]").attr("disabled", "disabled");
            return false;
        }
    </script>
{% endblock %}

bill/templates/bill/printbill.html
{% extends 'bill/base.htm' %}
{% block sectionTitle %}{% endblock %}
{% block content %}
    <table style="width:100%">
        <tr>
            <td colspan="10">
                <form id="form1" action="" method="POST">
                    <table style="text-align:left;width:60%;background-color:bue " >
                        <tr>
                            <td colspan="10" style="text-align:center;color:white;background-color: #ccccc0;color:black;font-weight:b;font-size:14px">Print Bill</td>
                        </tr>
                        <tr >
                            <td colspan="4"  style="background-color:#d3d3d3;font-size:13px;color:red;font-weight:bold;text-decoration:blink;text-align:center" > {{ varerr }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.session.label_tag }} &nbsp;{{ form.session }}</td>
                        </tr>
                        <tr>
                             <td>{{ form.klass.label_tag }}&nbsp;{{ form.klass }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.term.label_tag }}&nbsp;{{ form.term }}</td> 
                        </tr>
                        <tr>

                           <td>{{ form.name.label_tag }}&nbsp;{{ form.name }}</td> 
                         </tr>
                    </table>
                    <table>

                         <tr style='width=20%'>                              
                            <td>Print whole Class &nbsp;{{ form.excelfile }}</td>
                            
                        </tr>
                        <tr>
                            <td> Export to PDF &nbsp;{{ form.pdffile }}</td>
                            <td><input name="submit"  type="submit" value=":: View Bill ::"></td>
                        </tr>
                     <tr>
                           
                        </tr>

                    </table>
                </form>

            </td>
        </tr>
               <!-- <tr>

            <td colspan="10">
                <div class="box">


                </div>
            </td>
        </tr>-->
    </table>

    <script language="javascript" type="text/javascript">
        function disable(f)
        {
            var button = f.elements['submit'];
            button.value = 'Processing';
            button.disabled = 'true';
            return true;        }
    </script>
    <script>
        $(document).ready(function() {
            var pickerOpts = {
                //appendText: "mm/dd/yy",
                //defaultDate: "+5",
                showOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat:"yy-mm-dd"
                //showButtonPanel: true
                // showOn: "button"
            };

            getstudent();
            $("#id_session").keyup(function () {
                getstudent();
            });

            $("#id_klass").change(function () {
                getstudent();
            });

        });
    </script>
    <script type="text/javascript" language="javascript">
        function autopost(){
            var state = $("#id_session").val() + ':'+ $("#id_klass").val() + ':'+ $("#id_excelfile").val();

            alert(state);
            var url = "/bill/addajax/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    $(".box").show();
                    $(".box").html(html);
                }
            });
            //alert("error");
            return false;
        }
    </script>

    <script type="text/javascript" language="javascript">
        function getstudent(){
            var state = $("#id_session").val() + ':'+ $("#id_klass").val() ;
            //alert(state);
            var url = "/bill/getstudent/";
            var i = 0;
            var data='userid='+state;
            $("#id_name").val('');
            $("#id_name").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_name").append(options);
                    }
                })
            }
        }

    </script>
{% endblock %}

bill/templates/bill/success.html
{% extends 'bill/base.htm' %}
{% block sectionTitle %}Success{% endblock %}
{% block content %}

   <span style="font-size:20px;color:black;text-align:center;"> Welcome!!! Please select from the menus to the right of your screen</span>
{% endblock %}